baseURL = 'https://sultan-aloufi.github.io'
languageCode = 'en-us'
title = "Sultan Aloufi  🇸🇦"
theme = "PaperMod"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects"
weight = 20

[[menu.main]]
identifier = "about me"
name = "about me"
url = "/aboutme/"
wight = 30

[params.homeInfoParams]
Title =  "Sultan's home on the internet"
Content = "I write about Computers and share what I find interesting"

[[params.socialIcons]]
name = "Youtube"
url = "https://www.youtube.com/watch?v=LaVPQe8Zf9o"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/Sultan-Aloufi"

[[params.socialIcons]]
name = "Linkedin"
url = "https://www.linkedin.com/in/sultan-aloufi/"
